workflows:
  wikipedia-mac-mini-m2:
    name: Wikipedia Workflow with Mac mini M2
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "Wikipedia.xcodeproj"
        XCODE_SCHEME: "Wikipedia"
    scripts:
      - name: Upgrade brew
        script: brew install clang-format swiftlint || brew upgrade clang-format swiftlint
      - name: Installing scripts
        script: ./scripts/setup
      - name: Build
        script: |
          xcodebuild clean build -project $XCODE_PROJECT -scheme $XCODE_SCHEME -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

